### PR TITLE
Added remap

### PR DESCRIPTION
**Pull request by Andy-Python-Programmer**
I hope this gets merged! 🤞🏼

### CODE REVIEW

**Comment by Calamity210** [comment]
@Andy-Python-Programmer could you rename `n` to something like `value`. `n` gives no context on what the argument rly is

**Review by Calamity210 — CHANGES_REQUESTED** [review]
Please name parameters so they denote what they are meant for

**Comment by Andy-Python-Programmer** [comment]
Sure

**Comment by Calamity210** [comment]
LGTM

**Pull request merged**
