### PR TITLE
Windows!

### PR DESCRIPTION
**Pull request by Andy-Python-Programmer**
We have GUI support in birb! Hurray birb programmers!

# Progress
## Roots Are Not Deep But The Seeds Are Planted

The whole GUI system uses Open GL so no sacrifice here. We choose the best thing ie. not things like tkinter that have a **bad** UI.

### CODE REVIEW

**Comment by Andy-Python-Programmer** [comment]
Whoops by mistake I closed it. NVM fixed it. Btw everything works @Calamity210 and is ready for review!!!!!!!!!!!!

**Comment by Calamity210** [comment]
@Andy-Python-Programmer why is ui.birb in the root directory? Also be sure to add tests and documentation! :)

**Comment by Andy-Python-Programmer** [comment]
Thanks a lot @arj101 for giving the .so Dynamic File. Here is a demo showing that it works ( Also provided by him! )

linux-birb-ui-02
linux-birb-ui-01

CC @Calamity210

**Review by Calamity210 — COMMENTED** [review]
@Andy-Python-Programmer im leaving this PR open until we can get complete support for it

**Pull request closed without merging**
