### PR TITLE
Math

### PR DESCRIPTION
**Pull request by Andy-Python-Programmer**
Add birb:math

### CODE REVIEW

**Comment by Andy-Python-Programmer** [comment]
Tests are failing, why?

**Comment by Calamity210** [comment]
> Tests are failing, why?

`[e] FileSystemException: Cannot open file, path = './examples/core/packages' (OS Error: Is a directory, errno = 21)`

**Comment by Andy-Python-Programmer** [comment]
Done! Fixed

**Comment by AkramIzz** [comment]
This still has a bunch of unrelated edits, unwanted changes, and the commit messages don't explain the changes. Here's how to fix this:
1- create and checkout to a new branch from master:
    git checkout master && git checkout -b cleanup
2- cherry pick the related commits to cleanup:
    git cherry-pick commit_hash
3- if the cherry picked commit message can be improved change it:
    git commit --amend
4- if the commit itself includes unrelated changes you can edit it:
    git reset HEAD~1
 then add the related changes and commit them, stash the unrelated changes to be committed later in a relevant branch
   git stash save name-that-makes-it-easy-to-remember-what-the-changes-were
 you can see all the stashed changes using: 
    git stash list
 and apply the change when you need using: git stash stash@{index}
5- repeat step 2 and 4 for all related commits
6- push the new branch and create a new pull request
7- repeat steps 1 to 5 until all changes have been split into branches with the related changes

**Comment by AkramIzz** [comment]
ab268a27b6a3493a846668793d6593656435eadb delete birb.exe

1146c5cee752954f437cc236e9d0c58717eca5d2 gitignore .vscode directory

fdbd3e9962dc66eea8d9336a7103e34d2d61c19f add integer example, add runtimeType to double, fix runtime tests

a5ced20894f609dbae69b2f44e677ebb6edbf41e add math, rename integer and doubles examples to int and double

5de0d9c8a816d6276b44679d9de6f7b91a4df4e0 add birb standard packages short name birb

fdcef5ee4f40fa4581f3e8586cec6f2d722bcaa9 add list methods support in interpreter, add list example in core types

a218244de475ec10114c2e9d8f5632fdc483ce06 missing List.toString implementation

c5ec01f24d2de06cc16fc71b2bc296ecb3632154 fix tests fail: Directory structure

These are all the commit hashes for all the commits you did, with a more helpful commit message next to them

**Comment by Calamity210** [comment]
@Andy-Python-Programmer can you change the examples to be more relevant to real-life situations.
Some other changes I'd suggest are: 

```diff
  if (filename.startsWith('birb:')) {
-    filename = './packages/' + filename.split(':')[1] + '.birb';
+   filename = '${filename.replace('birb:', '../packages/')}.birb';
  }
```

as well as reverting the changes you made to tests, instead of your changes simply change `listSync()` to `listSync(recursive: true)`

**Pull request closed without merging**
